steps:
  # Access secrets for build
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=database-url > .env
        echo "JWT_SECRET=$(gcloud secrets versions access latest --secret=jwt-secret)" >> .env
        echo "NODE_ENV=production" >> .env
        echo "NEXT_TELEMETRY_DISABLED=1" >> .env
        cat .env

  # Get database URL and JWT secret for build args
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'get-secrets'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Store secrets in environment variables for the next step
        export DB_URL=$(gcloud secrets versions access latest --secret=database-url)
        export JWT=$(gcloud secrets versions access latest --secret=jwt-secret)
        # Store the secrets in files that will be available to the next step
        echo "$DB_URL" > /workspace/db_url.txt
        echo "$JWT" > /workspace/jwt.txt

  # Build the container image with build args from secrets
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        DB_URL=$(cat /workspace/db_url.txt)
        JWT=$(cat /workspace/jwt.txt)
        docker build \
          --build-arg DATABASE_URL="$DB_URL" \
          --build-arg JWT_SECRET="$JWT" \
          -t us-central1-docker.pkg.dev/${PROJECT_ID}/modernshop/app:${COMMIT_SHA} .

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/modernshop/app:${COMMIT_SHA}']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'modernshop'
      - '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/modernshop/app:${COMMIT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--update-secrets=DATABASE_URL=database-url:latest,JWT_SECRET=jwt-secret:latest'
      - '--set-env-vars=NODE_ENV=production,NEXT_TELEMETRY_DISABLED=1'

  # Apply database migrations
  - name: 'us-central1-docker.pkg.dev/${PROJECT_ID}/modernshop/app:${COMMIT_SHA}'
    entrypoint: npx
    args: ['prisma', 'migrate', 'deploy']
    secretEnv: ['DATABASE_URL']

substitutions:
  _REGION: us-central1

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/database-url/versions/latest
      env: 'DATABASE_URL'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/modernshop/app:${COMMIT_SHA}'