steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/modernshop/app:${COMMIT_SHA}', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/modernshop/app:${COMMIT_SHA}']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'modernshop'
      - '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/modernshop/app:${COMMIT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--update-secrets=DATABASE_URL=database-url:latest,JWT_SECRET=jwt-secret:latest'
      - '--set-env-vars=NODE_ENV=production,NEXT_TELEMETRY_DISABLED=1'

  # Apply database migrations
  - name: 'us-central1-docker.pkg.dev/${PROJECT_ID}/modernshop/app:${COMMIT_SHA}'
    entrypoint: npx
    args: ['prisma', 'migrate', 'deploy']
    secretEnv: ['DATABASE_URL']

substitutions:
  _REGION: us-central1

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/database-url/versions/latest
      env: 'DATABASE_URL'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/modernshop/app:${COMMIT_SHA}'