steps:
  # Create a .env file with dummy values for building
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "DATABASE_URL=postgresql://dummy:dummy@localhost:5432/dummy" > .env
        echo "JWT_SECRET=dummy-secret-for-build-only" >> .env
        echo "NODE_ENV=production" >> .env
        echo "NEXT_TELEMETRY_DISABLED=1" >> .env

  # Build the container image with dummy environment
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/modernshop/app:${COMMIT_SHA}', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/modernshop/app:${COMMIT_SHA}']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'modernshop'
      - '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/modernshop/app:${COMMIT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--update-secrets=DATABASE_URL=database-url:latest,JWT_SECRET=jwt-secret:latest'
      - '--set-env-vars=NODE_ENV=production,NEXT_TELEMETRY_DISABLED=1'

substitutions:
  _REGION: us-central1

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/modernshop/app:${COMMIT_SHA}'